name: build_opencv_ubu
on: workflow_dispatch

env:
  OPENCV_CONTRIB: 'https://github.com/opencv/opencv_contrib'
  ANT_HOME: '/usr/share/ant'
  PYTHONPATH: /opencv-contrib-build/python_loader:$PYTHONPATH
  EXTRA_CMAKE_OPTIONS: '-DCMAKE_INSTALL_PREFIX=/dist -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF  -DBUILD_PERF_TESTS=OFF -DWITH_OPENEXR=OFF -DBUILD_opencv_gapi=OFF -DWITH_ADE=OFF'

jobs:
  BuildAll:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    container:
      image: quay.io/asenyaev/opencv-ubuntu:20.04
    steps:
    - name: Init
      run: |
        mkdir -p /dist
        mkdir -p /opencv
        mkdir -p /opencv_contrib
        mkdir -p /opencv-contrib-build
        echo v 0017
    - name: Fetch
      run: |
       echo fetch contrib
       git clone https://github.com/opencv/opencv_contrib.git /opencv_contrib
       echo fetch main
       git clone https://github.com/opencv/opencv.git /opencv
    - name: Configure OpenCV
      run: |
        cd /opencv-contrib-build
        cmake -G Ninja ${{ env.EXTRA_CMAKE_OPTIONS }} -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules /opencv
    - name: Build OpenCV
      run: |
        cd /opencv-contrib-build
        ninja install

    - name: sim build
      run: |
       ls -l /dist
       echo 1 > /dist/1.txt
       echo 2 > /dist/2.txt
       echo 3 > /dist/3.txt
       
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: opencv
        path: /dist
       
