name: build_opencv_ubu
on: workflow_dispatch

env:
  OPENCV_CONTRIB: 'https://github.com/opencv/opencv_contrib'
  ANT_HOME: '/usr/share/ant'
  PYTHONPATH: /opencv-contrib-build/python_loader:$PYTHONPATH

jobs:
  BuildAll:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    container:
      image: quay.io/asenyaev/opencv-ubuntu:20.04
    steps:
#    - name: Init
#      run: |
#        mkdir /opencv
#        mkdir /opencv_contrib
#        mkdir /opencv-contrib-build
    - name: Fetch
      run: |
       git clone --single-branch https://github.com/opencv/opencv.git /opencv
       git clone --single-branch https://github.com/opencv/opencv_cotrib.git /opencv_contrib
    - name: Configure OpenCV
      run: |
        cd /opencv-contrib-build
        cmake -G Ninja ${{ env.EXTRA_CMAKE_OPTIONS }} -DOPENCV_EXTRA_MODULES_PATH=${{ env.OPENCV_CONTRIB_DOCKER_WORKDIR }}/modules /opencv
    - name: Build OpenCV
      run: |
        cd /opencv-contrib-build
        ninja
