name: build_opencv_ubu
on: workflow_dispatch

env:
  OPENCV_CONTRIB: 'https://github.com/berak/opencv_contrib -b patch-1' # mcc patch
  ANT_HOME: '/usr/share/ant'
  PYTHONPATH: /opencv-contrib-build/python_loader:$PYTHONPATH
  EXTRA_CMAKE_OPTIONS: '-DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF  -DBUILD_PERF_TESTS=OFF -DWITH_OPENEXR=OFF -DBUILD_opencv_gapi=OFF -DWITH_ADE=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_apps=OFF '

jobs:
  BuildAll:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    container:
      image: quay.io/asenyaev/opencv-ubuntu:20.04
    steps:
    - name: Init
      run: |
        mkdir -p /dist
        mkdir -p /opencv
        mkdir -p /opencv_contrib
        mkdir -p /opencv-contrib-build
        echo v 0023
    - name: Fetch
      run: |
       echo fetch contrib
       git clone ${{ env.OPENCV_CONTRIB }} /opencv_contrib
       echo fetch main
       git clone https://github.com/opencv/opencv.git /opencv
    - name: Configure OpenCV
      run: |
        cd /opencv-contrib-build
        cmake -G Ninja ${{ env.EXTRA_CMAKE_OPTIONS }} -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules/mcc /opencv
    - name: Build OpenCV
      run: |
        cd /opencv-contrib-build
        ninja

    - name: keep java
      run: |
       ls -l /dist
       cp /opencv-contrib-build/lib/libopencv_java455.so /dist
       cp /opencv-contrib-build/bin/opencv-455.jar /dist
       
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: opencv
        path: /dist
       
