name: build_opencv_ubu
on: workflow_dispatch

env:
  OPENCV_CONTRIB: 'https://github.com/opencv/opencv_contrib'
  ANT_HOME: '/usr/share/ant'
  PYTHONPATH: /opencv-contrib-build/python_loader:$PYTHONPATH
  EXTRA_CMAKE_OPTIONS: ''

jobs:
  BuildAll:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    container:
      image: quay.io/asenyaev/opencv-ubuntu:20.04
    steps:
    - name: Init
      run: |
        mkdir -p /opencv
        mkdir -p /opencv_contrib
        mkdir -p /opencv-contrib-build
        ls -l 
    - name: Fetch
      run: |
       echo fetch contrib
       git clone https://github.com/opencv/opencv_contrib.git /opencv_contrib
       echo fetch main
       git clone https://github.com/opencv/opencv.git /opencv
    - name: Configure OpenCV
      run: |
        cd /opencv-contrib-build
        cmake -G Ninja ${{ env.EXTRA_CMAKE_OPTIONS }} -DOPENCV_EXTRA_MODULES_PATH=/opencv_contrib/modules /opencv
 #   - name: Build OpenCV
 #     run: |
 #       cd /opencv-contrib-build
 #       ninja
