name: build_opencv_andro
on: workflow_dispatch

env:
  OPENCV_CONTRIB: 'https://github.com/berak/opencv_contrib -b patch-1' # mcc patch
  ANT_HOME: '/usr/share/ant'
  EXTRA_CMAKE_OPTIONS: '-DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF  -DBUILD_PERF_TESTS=OFF -DWITH_OPENEXR=OFF -DBUILD_opencv_gapi=OFF -DWITH_ADE=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_apps=OFF '

jobs:
  BuildAll:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    container:
      image: quay.io/asenyaev/opencv-ubuntu:20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Init
      run: |
        mkdir -p /dist
        mkdir -p /opencv
        mkdir -p /opencv_contrib
        mkdir -p /opencv-contrib-build
        echo v 0002
    - name: Fetch
      run: |
       echo fetch contrib
       git clone ${{ env.OPENCV_CONTRIB }} /opencv_contrib
       echo fetch main
       git clone https://github.com/opencv/opencv.git /opencv
    - name: Run Platform Build
      run: |
        cd /opencv/platforms/android
        ls -l
        python3 /opencv/platforms/android/build_sdk.py --extra_modules_path=/opencv_contrib/modules/mcc
